#!/bin/bash

MYSQL="mysql -s -u -p gemini";
OWNDR="/var/cluster/changes";

if [ ! -f "$OWNDR/ref_zones.txt" ]; then
        echo "select md5(concat(zone,nameserver,nodes)) from zones order by id;" | $MYSQL > "$OWNDR/ref_zones.txt"
else
        echo "select md5(concat(zone,nameserver,nodes)) from zones order by id;" | $MYSQL > "$OWNDR/tst_zones.txt"

        if ( diff "$OWNDR/ref_zones.txt" "$OWNDR/tst_zones.txt" >/dev/null ); then
                rm "$OWNDR/tst_zones.txt";
                if [ ! -f "$OWNDR/ref_records.txt" ]; then
                        echo "select md5(concat(name,type,value)) from records order by id;" | $MYSQL > "$OWNDR/ref_records.txt"
                else
                        echo "select md5(concat(name,type,value)) from records order by id;" | $MYSQL > "$OWNDR/tst_records.txt"
                        if ( diff "$OWNDR/ref_records.txt" "$OWNDR/tst_records.txt" >/dev/null ); then
                                rm "$OWNDR/tst_records.txt";
                        else
                                cp "$OWNDR/tst_records.txt" "$OWNDR/ref_records.txt";
                                rm "$OWNDR/tst_records.txt";
                                /root/tools/cluster_bindcfg.pl
                        fi
                fi
        else
                cp "$OWNDR/tst_zones.txt" "$OWNDR/ref_zones.txt";
                rm "$OWNDR/tst_zones.txt";
                /root/tools/cluster_bindcfg.pl
        fi
fi

if [ ! -f "$OWNDR/ref_vhosts.txt" ]; then
        echo "select md5(concat(server,alias,nginxrw,uid,gid,nodes)) from vhosts order by id;" | $MYSQL > "$OWNDR/ref_vhosts.txt"
else
        echo "select md5(concat(server,alias,nginxrw,uid,gid,nodes)) from vhosts order by id;" | $MYSQL > "$OWNDR/tst_vhosts.txt"
        if ( diff "$OWNDR/ref_vhosts.txt" "$OWNDR/tst_vhosts.txt" >/dev/null ); then
                rm "$OWNDR/tst_vhosts.txt";
        else
                cp "$OWNDR/tst_vhosts.txt" "$OWNDR/ref_vhosts.txt";
                rm "$OWNDR/tst_vhosts.txt";
                /root/tools/cluster_nginx.pl
                /etc/init.d/nginx stop
                /etc/init.d/spawn-fcgi.php stop
                /etc/init.d/spawn-fcgi.php start
                /etc/init.d/nginx start
        fi
fi
