#!/bin/bash

TDAY=`date +%d/%b/%Y`;
date +"%d-%m-%Y %H:%M" >> /var/log/sys/access.log
ls /var/log/nginx/*.*.log | while read l; do
	l=`echo $l | sed -e "s/\/var\/log\/nginx\///"`;
	VNM=`echo $l | sed -e "s/\.log//"`;
	HITS=`grep "$TDAY" "/var/log/nginx/$l" | wc -l`;
	UNIQ=`grep "$TDAY" "/var/log/nginx/$l" | awk '{print $1;}' | sort -u | wc -l`;
	TRAF=0;
	FSIZ=`grep "$TDAY" "/var/log/nginx/$l" | awk '{print $10;}'`;
	for fs in $FSIZ; do
		if echo "$fs" | grep -e "^[0-9]\+$" >/dev/null; then
			TRAF=$((TRAF+fs));
		fi
	done
	if [ $TRAF -ge 1073741824 ]; then
		TRAF="\033[0;31m"$((TRAF/1073741824))"G\033[00m";
	else
		if [ $TRAF -ge 1048576 ]; then
			TRAF=$((TRAF/1048576))"M";
		else
			[ $TRAF -ge 1024 ] && TRAF=$((TRAF/1024))"k";
		fi
	fi
	PADS="";
	[ ${#VNM} -le 31 ] && PADS="$PADS\t";
	[ ${#VNM} -le 23 ] && PADS="$PADS\t";
	[ ${#VNM} -le 15 ] && PADS="$PADS\t";
	[ ${#VNM} -le 7 ] && PADS="$PADS\t";
	STATS="$VNM\t$PADS${HITS% *}\t$UNIQ\t$TRAF";
	echo -e $STATS >> /var/log/sys/access.log;

	echo '' > /var/log/nginx/$l;
done
