#!/bin/bash

eerror () {
        echo -e " \033[0;31m*\033[00m" $1;
        }
ebegin () {
        echo -e " \033[1;32m*\033[00m" $1;
        }
einfo () {
        echo -e " \033[0;35m*\033[00m" $1;
        }
eend () {
        if [[ $1 -eq 0 ]]; then
                echo -e -n "\033[s\033[1A\033[$((COLUMNS-6))C[\033[1;32mok\033[00m]\033[u";
        else
                echo -e -n "\033[s\033[1A\033[$((COLUMNS-6))C[\033[0;31m!!\033[00m]\033[u";
                exit 1;
        fi
        }

ebegin "Retrieving latest WordPress version ...";
cd /mnt/www/
wget -q -q -O wordpress.zip http://wordpress.org/latest.zip
eend;
ebegin "Unzipping ...";
unzip -qq wordpress.zip
eend;
ebegin "Cleaning ...";
rm wordpress.zip
eend;

ls | while read i
do
	if [ -d /mnt/www/$i/$i/wp-admin ]
	then
		einfo "Checking /mnt/www/$i/$i/wp-admin ..."
		ebegin "Removing wp-admin ..."
		rm -Rf /mnt/www/$i/$i/wp-admin
		ebegin "Removing wp-includes ..."
		rm -Rf /mnt/www/$i/$i/wp-includes
		ebegin "Updating files ..."
		cp -r /mnt/www/wordpress/* /mnt/www/$i/$i/
		ebegin "Regaining ownership ..."
		chown -R websrv:websrv /mnt/www/$i/$i/*
	fi
	if [ -d /mnt/www/$i/$i/ro/wp-admin ]
	then
		einfo "Checking /mnt/www/$i/$i/ro/wp-admin ..."
		ebegin "Removing wp-admin ..."
		rm -Rf /mnt/www/$i/$i/ro/wp-admin
		ebegin "Removing wp-includes ..."
		rm -Rf /mnt/www/$i/$i/ro/wp-includes
		ebegin "Updating files ..."
		cp -r /mnt/www/wordpress/* /mnt/www/$i/$i/ro/
		ebegin "Regaining ownership ..."
		chown -R websrv:websrv /mnt/www/$i/$i/ro/*
	fi
done

ebegin "Cleaning ...";
rm -Rf /mnt/www/wordpress && eend;
