# PostgreSQL configuration file
# Generated by site-builder

# Connection settings
{% if DB_MODE == "docker" -%}
listen_addresses = '*'
{% else -%}
listen_addresses = 'localhost'
{% endif -%}
port = 5432
max_connections = {{ DB_MAX_CONNECTIONS | default('100') }}

# Memory settings
shared_buffers = {{ DB_SHARED_BUFFERS | default('128MB') }}
work_mem = {{ DB_WORK_MEM | default('4MB') }}
maintenance_work_mem = {{ DB_MAINTENANCE_WORK_MEM | default('64MB') }}
effective_cache_size = {{ DB_EFFECTIVE_CACHE_SIZE | default('1GB') }}

# Write-ahead log settings
wal_buffers = {{ DB_WAL_BUFFERS | default('16MB') }}
checkpoint_completion_target = {{ DB_CHECKPOINT_COMPLETION_TARGET | default('0.9') }}

# Query planner settings
random_page_cost = {{ DB_RANDOM_PAGE_COST | default('1.1') }}
effective_io_concurrency = {{ DB_EFFECTIVE_IO_CONCURRENCY | default('200') }}

# Logging settings
log_destination = 'stderr'
logging_collector = {{ DB_LOGGING_COLLECTOR | default('on') }}
log_directory = '/var/log/postgresql'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
log_rotation_age = {{ DB_LOG_ROTATION_AGE | default('1d') }}
log_rotation_size = {{ DB_LOG_ROTATION_SIZE | default('10MB') }}

# What to log
log_min_duration_statement = {{ DB_LOG_MIN_DURATION_STATEMENT | default('1000') }}  # Log queries longer than 1 second
log_statement = '{{ DB_LOG_STATEMENT | default("none") }}'  # none, ddl, mod, all
log_line_prefix = '{{ DB_LOG_LINE_PREFIX | default("%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h ") }}'

# Locale settings
lc_messages = '{{ DB_LC_MESSAGES | default("en_US.UTF-8") }}'
lc_monetary = '{{ DB_LC_MONETARY | default("en_US.UTF-8") }}'
lc_numeric = '{{ DB_LC_NUMERIC | default("en_US.UTF-8") }}'
lc_time = '{{ DB_LC_TIME | default("en_US.UTF-8") }}'

# Default text search configuration
default_text_search_config = '{{ DB_DEFAULT_TEXT_SEARCH_CONFIG | default("pg_catalog.english") }}'

# Security settings
{% if DB_MODE == "native" -%}
# Enable SSL for native installations
ssl = on
ssl_cert_file = '/etc/ssl/certs/ssl-cert-snakeoil.pem'
ssl_key_file = '/etc/ssl/private/ssl-cert-snakeoil.key'
{% endif -%}

# Performance tuning
autovacuum = {{ DB_AUTOVACUUM | default('on') }}
track_activities = {{ DB_TRACK_ACTIVITIES | default('on') }}
track_counts = {{ DB_TRACK_COUNTS | default('on') }}

# Connection pooling (if using pgbouncer)
{% if DB_ENABLE_PGBOUNCER | default(false) -%}
# pgbouncer configuration would go here
{% endif -%}
